### ISSUE TITLE
Rigidbody values such as angularDamping don't seem to be applied when game starts

### ISSUE THREAD

**Issue by VoxelBoy** [Phong13/BulletSharpUnity3d#30]
I've pulled the latest commit ([78259c9](https://github.com/Phong13/BulletSharpUnity3d/commit/78259c9ec9fb421ce11e2843f3878c8711497909) as of now) and tested this several times to make sure I wasn't missing something.

Here's a recording of the problem:
https://dl.dropboxusercontent.com/u/561110/ballThrow_angularDamping_NoEffect.mp4

Here's the placeholder fix applied just to show how it's supposed to work:
https://dl.dropboxusercontent.com/u/561110/rbTempFix.JPG

Here's a recording of angularDamping working after the placeholder fix:
https://dl.dropboxusercontent.com/u/561110/ballThrow_angularDamping_WorkingCorrectly.mp4

**Comment by Phong13** [comment]
You are right. It is a bug. I have checked in a fix.
