### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by hcorion** [Phong13/BulletSharpUnity3d#38]
Hi, I just imported your asset from the Unity asset Store, and as I expected Linux support is not there. I tried compiling libbulletc from your fork of BulletSharpPInvoke but I only got a bunch of libBulletCollision.a, libLinearMath.a etc. I tried copying the libbulletc.so from something I downloaded here:  http://andrestraks.github.io/BulletSharp/ but Unity still throws a DllNotFoundException libbulletc.

I am using the Linux Unity editor version 5.5.1xf1Linux Personal.

**Comment by Phong13** [comment]
Hello, I plan on adding support for Linux but have not gotten around to it. Some in the forums has compiled the linux library but did not share the build files. The library can be dowloaded here

https://forum.unity3d.com/threads/released-bullet-physics-for-unity.408154/page-3

**Comment by hcorion** [comment]
No dice, 
I tried the provided zip, extracted it to the bulletunity native folder in a linux subdirectory, still said  DllNotFoundException libbulletc.

**Comment by Phong13** [comment]
Did you assign which platforms it should be used for in the inspector? It is not enough just to put it in a linux folder. Select the .so and check the inspector.

**Comment by hcorion** [comment]
Yeah, I selected the .so, Made sure the cpu is x86_64, OS is Linux in the editor section and in the PC, Mac & standalone section I selected Linux x86_64. I even ran ldd ( to see what it was linked to ) and there were no unlinked files:
```
linux-vdso.so.1 (0x00007fff9558d000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f3acc6bc000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f3acc3b8000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3acc1a1000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3acbe03000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x000055f4c2921000)
```

**Comment by hcorion** [comment]
Hah, I figured it out, I'll make a pull request.
