### ISSUE TITLE
DllNotFoundException on Android 6.0.1

### ISSUE THREAD

**Issue by haolly** [Phong13/BulletSharpUnity3d#42]
It's works fine on unity editor, and some other Android device， but my newer device which run Android 6.0.1 do not work,  I guess the libbulletc may depends some other librarys which do not exists in the device, 
but I maybe I am wrong

**Comment by Phong13** [comment]
Hi haolly,

I believe that Unity only offically, supports ARMv7 and x86 Android devices when using native plugins. Is your device by chance not ARMv7 or x86?

**Comment by haolly** [comment]
It turned out to be that I was not using the latest version.  close issue

**Comment by haolly** [comment]
Actually, this issue still exists,  #43  will fix this
