### ISSUE TITLE
Debug draws of boxes are twice as big

### ISSUE THREAD

**Issue by tsornin** [Phong13/BulletSharpUnity3d#45]
https://github.com/Phong13/BulletSharpUnity3d/blob/d3cca380abfb8a96405fcaa6fd781d9d47de549f/UnityProject/Assets/BulletUnity/Scripts/DebugDrawUnity.cs#L29

This size needs to be halved because box size is a half-extent in Bullet:
`UnityEngine.Vector3 size = (bbMax - bbMin).ToUnity() / 2;`

**Comment by Phong13** [comment]
Thanks, I will fix.

**Comment by WeersProductions** [comment]
#56
