### ISSUE TITLE
Libbulletc.dll will cause unit to crash

### ISSUE THREAD

**Issue by yhr28** [Phong13/BulletSharpUnity3d#71]
Libbulletc.dll will cause unity Editor to crash. Can you generate a new version of. NETCORE?
Thanks!

**Comment by yhr28** [comment]
Libbulletc.dll will cause unity Eiditor to crash. Can you generate a new version of. NETCORE?
Thanks!

**Comment by Phong13** [comment]
Will do over the next day or two.

**Comment by yhr28** [comment]
> Will do over the next day or two.

Thank!!!

**Comment by Phong13** [comment]
I am looking into this but cannot reproduce the crash. Can you provide more details about your setup?

Unity version, OS, Build Platform, Player Settings, Any settings related to the .NET you are using (scripting backend, API Compatibility Level).

**Comment by Phong13** [comment]
Also I noticed you closed this, did the problem go away?
