### ISSUE TITLE
AllConvexResultCallback

### ISSUE THREAD

**Issue by nagedev** [Phong13/BulletSharpUnity3d#75]
As I understand, ConvexResultCallback is inherited by only one class (ClosestConvexResultCallback), and because of that ConvexSweepTest returns only closest result, which means that there's no way to get All collisions

Is there any way to do some shape cast that returns all collisions?

**Comment by Phong13** [comment]
Have you tried using a ghost object? I think you can:

Create a ghost object
Add your casting shape
Move it and there should be a collision pair cache that has all the collisions.

**Comment by nagedev** [comment]
That works!
I thought it would require calling StepSimulation, but it works perfectly without it
Thanks
